module.exports = {
  purge: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
    },
    extend: {
      colors: {
        gray: {
          900: 'black',
          200: 'black',
          300: 'black',
          400: 'black',
          500: 'black',
          600: 'black',
          700: 'black',
          800: 'black',
          100: 'black',
        },
        blue: {
          100: 'black',
          200: 'black',
          300: 'black',
          400: 'black',
          500: 'black',
          600: 'black',
          700: 'black',
          800: 'black',
          900: 'black',
        },
      },
    },
  },
  variants: {
    borderColor: ['responsive', 'hover'],
    borderStyle: ['responsive', 'last', 'hover'],
    borderWidth: ['responsive', 'hover'],
    margin: ['responsive', 'first'],
    transform: ['responsive', 'hover'],
  },
  plugins: [],
};
